platform: linux

image_resource:
  type: docker-image
    source: {repository: busybox}
    inputs:
      - name: hello-source
      run:
        path: cat
        args: [
            "build.yml"
        ]
